drinkwater/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import homePage
from user.views import *
from django.conf import settings
from django.conf.urls.static import static
from water.views import user_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name="home"),
    path('user/', include('user.urls')),
    path('userpage/', user_page, name="userpage"),
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views

app_name='user'

urlpatterns=[
    path('register', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),

]

templates/includes/messages.html
<div class="container mt-5">
    <div class="d-flex justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                        <div class="alert alert-{{message.tags}}"><a style="text-decoration:none;" href="{% url 'home' %}"><p class="text-center">{{ message }}</p></a></div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

templates/includes/navbar.html
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand ml-3" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav ml-auto mr-5">
               {% if request.user.is_authenticated %}
               <li class="nav-item mx-3">
                   <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
               </li>
               <li class="nav-item mx-3">
                   <a class="nav-link" href="{% url 'userpage' %}">User Page</a>
               </li>
               {% else %}
                <li class="nav-item mx-3">
                   <a class="nav-link" href="{% url 'user:login' %}">Login<span class="sr-only">(current)</span></a>
               </li>
               <li class="nav-item mx-3">
                   <a class="nav-link" href="{% url 'user:register' %}">Register</a>
               </li>
               {% endif %}
           </ul>
    </div>
</nav>